GestionPlanning/Controllers/ArmesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using GestionPlanning.Abstract;
using GestionPlanning.Enum;
using GestionPlanning.Models;

namespace GestionPlanning.Controllers
{
    /// <summary>
    /// Controleur pour la gestion des armes des utilisateurs
    /// </summary>
    [Authorize(Roles = "ADMINISTRATEUR")]
    public class ArmesController : AbstractControl
    {
        /// <summary>
        /// Chage la page de la liste des armes
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(Db.Armes.ToList());
        }

        /// <summary>
        /// Charge la page des détails d'une arme
        /// </summary>
        /// <param name="id">l'id d'une arme</param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var armes = Db.Armes.Find(id);
            if (armes == null)
            {
                return HttpNotFound();
            }
            return View(armes);
        }

        /// <summary>
        /// Charge la page de création d'une arme
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View(new Armes {Etat = EtatEnum.ACTIF});
        }
        
        /// <summary>
        /// Créer une nouelle arme
        /// </summary>
        /// <param name="armes">la nouvelle arme</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Armes armes)
        {
            if (ModelState.IsValid)
            {
                //sauvegarde en base
                armes.Etat = EtatEnum.ACTIF;
                Db.Armes.Add(armes);
                Db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(armes);
        }

        /// <summary>
        /// CHarge la page des édition d'une arme
        /// </summary>
        /// <param name="id">l'id de l'arme à modifier</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var armes = Db.Armes.Find(id);
            if (armes == null)
            {
                return HttpNotFound();
            }
            return View(armes);
        }
        
        /// <summary>
        /// modifie une arme
        /// </summary>
        /// <param name="armes">l'amre modifiée</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Armes armes)
        {
            if (ModelState.IsValid)
            {
                armes.Etat = EtatEnum.ACTIF;
                Db.Entry(armes).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(armes);
        }

        /// <summary>
        /// charge la page de suppression d'une arme
        /// </summary>
        /// <param name="id">l'id de l'arme à supprimer</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var armes = Db.Armes.Find(id);
            if (armes == null)
            {
                return HttpNotFound();
            }
            return View(armes);
        }

        /// <summary>
        /// Supprime une arme en base (la périme)
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var armes = Db.Armes.Find(id);
            armes.Etat = EtatEnum.PERIME;
            Db.Entry(armes).State = EntityState.Modified;
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionPlanning/Controllers/GradesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using GestionPlanning.Abstract;
using GestionPlanning.Enum;
using GestionPlanning.Models;

namespace GestionPlanning.Controllers
{
    /// <summary>
    /// Controleur de gesion des grades
    /// </summary>
    [Authorize(Roles = "ADMINISTRATEUR")]
    public class GradesController : AbstractControl
    {
        /// <summary>
        /// Charge la page d'index des grades
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var grades = Db.Grades.Where(x=> x.Etat == EtatEnum.ACTIF).Include(g => g.Armes);
            return View(grades.ToList());
        }

        /// <summary>
        /// Charge la page des détails d'un grade
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var grades = Db.Grades.Find(id);
            if (grades == null)
            {
                return HttpNotFound();
            }
            return View(grades);
        }

        /// <summary>
        /// Charge la page de création d'un grade
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            ViewBag.ArmesId = new SelectList(Db.Armes, "Id", "Nom");
            return View(new Grades {Etat = EtatEnum.ACTIF});
        }
        
        /// <summary>
        /// Créer un grade
        /// </summary>
        /// <param name="grades">le grade à créer</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Grades grades)
        {
            if (ModelState.IsValid)
            {
                grades.Etat = EtatEnum.ACTIF;
                Db.Grades.Add(grades);
                Db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArmesId = new SelectList(Db.Armes, "Id", "Nom", grades.ArmesId);
            return View(grades);
        }

        /// <summary>
        /// Charge la page de modification d'un grade
        /// </summary>
        /// <param name="id">l'id du grade à modifier</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var grades = Db.Grades.Find(id);
            if (grades == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArmesId = new SelectList(Db.Armes, "Id", "Nom", grades.ArmesId);
            return View(grades);
        }
        
        /// <summary>
        /// Modifie un grade
        /// </summary>
        /// <param name="grades">le grade modifié</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Diminutif,ArmesId,Etat")] Grades grades)
        {
            if (ModelState.IsValid)
            {
                grades.Etat = EtatEnum.ACTIF;
                Db.Entry(grades).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArmesId = new SelectList(Db.Armes, "Id", "Nom", grades.ArmesId);
            return View(grades);
        }

        /// <summary>
        /// charge la page pour supprimer un grade
        /// </summary>
        /// <param name="id">l'id du grade à supprimer</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var grades = Db.Grades.Find(id);
            if (grades == null)
            {
                return HttpNotFound();
            }
            return View(grades);
        }

        /// <summary>
        /// Périme un grade
        /// </summary>
        /// <param name="id">l'id du grade à périmer</param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var grades = Db.Grades.Find(id);
            grades.Etat = EtatEnum.PERIME;
            Db.Entry(grades).State = EntityState.Modified;
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionPlanning/Controllers/MailsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using GestionPlanning.Abstract;
using GestionPlanning.Models;

namespace GestionPlanning.Controllers
{
    /// <summary>
    /// Controleur pour la gestion des mails
    /// </summary>
    [Authorize(Roles = "ADMINISTRATEUR")]
    public class MailsController : AbstractControl
    {
        /// <summary>
        /// Chage la page du listing des mails
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(Db.Mails.ToList());
        }
        
        /// <summary>
        /// charge la page de modification d'un mail
        /// </summary>
        /// <param name="id">l'id du mail à modifier</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var mails = Db.Mails.Find(id);
            if (mails == null)
            {
                return HttpNotFound();
            }
            return View(mails);
        }
        
        /// <summary>
        /// modifie un mail
        /// </summary>
        /// <param name="mails">le mail à modifier</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Mails mails)
        {
            if (ModelState.IsValid)
            {
                var mail = Db.Mails.Find(mails.Id);
                mail.Corps = mails.Corps;
                mail.Objet = mail.Objet;
                if (mail != null)
                {
                    Db.Entry(mail).State = EntityState.Modified;
                    Db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(mails);
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionPlanning/Controllers/PolesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using GestionPlanning.Abstract;
using GestionPlanning.Enum;
using GestionPlanning.Models;

namespace GestionPlanning.Controllers
{
    /// <summary>
    /// Controleur pour le gestion des poles
    /// </summary>
    [Authorize(Roles = "ADMINISTRATEUR")]
    public class PolesController : AbstractControl
    {

        /// <summary>
        /// Charge la page d'index des poles
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(Db.Poles.Where(x => x.Etat == EtatEnum.ACTIF).ToList());
        }

        /// <summary>
        /// CHarge la page de détails d'un pole
        /// </summary>
        /// <param name="id">l'id du pole</param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var poles = Db.Poles.Find(id);
            if (poles == null)
            {
                return HttpNotFound();
            }
            return View(poles);
        }

        /// <summary>
        /// Charge la page de création d'un pole
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var pole = new Poles
            {
                Etat = EtatEnum.ACTIF
            };
            return View(pole);
        }

        /// <summary>
        /// Créer un pole
        /// </summary>
        /// <param name="poles">le pole à créer</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Poles poles)
        {
            if (ModelState.IsValid)
            {
                poles.Etat = EtatEnum.ACTIF;
                Db.Poles.Add(poles);
                Db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(poles);
        }

        /// <summary>
        /// Charge la page de modification d'un pole
        /// </summary>
        /// <param name="id">l'id du pole à modifier</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var poles = Db.Poles.Find(id);
            if (poles == null)
            {
                return HttpNotFound();
            }
            return View(poles);
        }

        /// <summary>
        /// Modifie un pole
        /// </summary>
        /// <param name="poles">le pole à modifier</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Poles poles)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(poles).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(poles);
        }

        /// <summary>
        /// Charge la page de supression d'un pole
        /// </summary>
        /// <param name="id">l'id du pole à supprimer</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poles poles = Db.Poles.Find(id);
            if (poles == null)
            {
                return HttpNotFound();
            }
            return View(poles);
        }

        /// <summary>
        /// Supprime un pole
        /// </summary>
        /// <param name="id">le pole à périmer</param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var poles = Db.Poles.Find(id);
            poles.Etat = EtatEnum.PERIME;
            Db.Entry(poles).State = EntityState.Modified;
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionPlanning/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

GestionPlanning/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

GestionPlanning/Views/Shared/_Layout.cshtml
@using GestionPlanning.Context
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (@User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Bonjour " + @User.Identity.Name, "Index", "Planning", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Login", "Login", "Auth", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a href="@Url.Action("Logout", "Auth")"> Déconnexion</a>
                        </li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Index", "Planning")"> Planning</a></li>
                        <li><a href="@Url.Action("ListingRepas", "Repas")"> Repas</a></li>
                        <li><a href="@Url.Action("Annuaire", "Utilisateurs")"> Annuaire</a></li>
                    }
                </ul>
                <span style="color: grey; font-size: 20px; font-weight: bolder; margin-left: 200px;">@ContexteApplication.Application.NomAppli - @ContexteApplication.Application.NomUnite</span>
            </div>

        </div>
    </div>

<div class="container body-content">
    <table>
        <tr>
            <td style="vertical-align: top;">
               @RenderPage("_Menu.cshtml")
            </td>

            <td style="width:100%">
                @RenderBody()
            </td>
        </tr>
    </table>
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - @ContexteApplication.Application.NomAppli - Version : @ContexteStatic.Version</p>
    </footer>
</div>

</body>
</html>

GestionPlanning/Views/Shared/_Menu.cshtml
@using GestionPlanning.Context
@using GestionPlanning.Enum
@if (@User.Identity.IsAuthenticated)
{

    <div class="menu-left">
        @if (@User.IsInRole(RoleEnum.ADMINISTRATEUR.ToString()))
        {
            <p class="title-menu-left">Administration</p>
            <hr style="text-align: center; width: 75%;"/>
            <ul>
                <li>@Html.ActionLink("Logs", "Logs", "Applications")</li>
                <li>@Html.ActionLink("Gestion de l'Application", "Edit", "Applications")</li>
                <li>@Html.ActionLink("Gestion des types d'activités", "Index", "TypeActivites")</li>
                <li>@Html.ActionLink("Gestion des pôles", "Index", "Poles")</li>
                <li>@Html.ActionLink("Gestion des armes", "Index", "Armes")</li>
                <li>@Html.ActionLink("Gestion des grades", "Index", "Grades")</li>
                <li>@Html.ActionLink("Gestion des emails", "Index", "Mails")</li>
                <li>@Html.ActionLink("Gestion des utilisateurs", "Index", "Utilisateurs")</li>
                <li>@Html.ActionLink("Gestion des permissions", "Index", "Permissions")</li>
            </ul>
        }


        @if ((@User.IsInRole(RoleEnum.ADMINISTRATEUR.ToString()) || @User.IsInRole(RoleEnum.UTILISATEUR.ToString())) && (@User.Identity.Name != ContexteStatic.NomSuperAdmin+" "+ContexteStatic.PrenomSuperAdmin))
        {
            <p class="title-menu-left">Mon compte</p>
            <hr style="text-align: center; width: 75%;"/>
            <ul>
                <li>@Html.ActionLink("Informations personnelles", "ChangeInfoPerso", "Utilisateurs")</li>
                <li>@Html.ActionLink("Mes activités", "Index", "Activites")</li>
                <li>@Html.ActionLink("Mes évènements", "MesEvenements", "Evenements")</li>
                <li>@Html.ActionLink("Mon pointage repas", "PlanningMessPerso", "Repas")</li>
            </ul>
        }
        <p class="title-menu-left">Outils</p>
        <hr style="text-align: center; width: 75%;" />
        <ul>
            <li>@Html.ActionLink("Planning", "Index", "Planning")</li>
            <li>@Html.ActionLink("Listing des repas", "ListingRepas", "Repas")</li>
            <li>@Html.ActionLink("Annuaire", "Annuaire", "Utilisateurs")</li>
        </ul>


        <hr style="text-align: center; width: 75%;" />
    </div>
}