GestionPlanning/Controllers/PlanningController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web.Mvc;
using GestionPlanning.Abstract;
using GestionPlanning.Enum;
using GestionPlanning.Utils;
using GestionPlanning.ViewModel;

namespace GestionPlanning.Controllers
{
    /// <summary>
    /// Controleur du calendrier
    /// </summary>
    [Authorize(Roles = "ADMINISTRATEUR,UTILISATEUR")]
    [AllowAnonymous]
    public class PlanningController : AbstractControl
    {
        /// <summary>
        /// Retourne le viewModel à afficher à partir de la date
        /// </summary>
        /// <param name="date">la date de début</param>
        /// <returns>l'objet</returns>
        private UserDateEventViewModel GetData(DateTime date)
        {
            var dateFinMois = DateUtils.GetEndMoisDate(date);
            var dateDebut = new DateTime(date.Year, date.Month, 1);
            var listeArme = Db.Armes.ToList();

            //chargement des données de bases (les activités existante, les utilisateurs, la date du jour)
            var data = new UserDateEventViewModel
            {
                IdUserEnCours = (User?.Identity != null && User.Identity.IsAuthenticated)?GetIdUtilisateurConnecte():0,
                ListeTypesActivites =  Db.TypeActivites.Where(x => x.Etat == EtatEnum.ACTIF).ToList(),
                ListeUtilisateurs = Db.Utilisateurs.Where(x => x.Etat == EtatEnum.ACTIF)
                                                    .OrderBy(x => x.Poles.Nom)
                                                    .ThenBy(x=> x.Nom)
                                                    .ThenBy(x => x.Prenom)
                                                    .ToList(),
                DateEnCours = date,
                Annee = date.Year.ToString(),
                Mois = DateUtils.GetNomMois(date)
            };
            
            //chargement des activités, des armes et des évènements
            foreach (var utilisateur in data.ListeUtilisateurs)
            {
                utilisateur.Activites = Db.Activites.Where(x => x.UtilisateurId == utilisateur.Id && x.DateDebut>= dateDebut && x.DateFin <= dateFinMois).ToList();
                utilisateur.EvenementsUtilisateurs =  Db.EvenementsUtilisateurs.Where(x => x.UtilisateursId == utilisateur.Id && x.IsPresent.HasValue && x.IsPresent.Value && x.DateSelected.HasValue && x.DateSelected.Value <= dateFinMois && x.DateSelected.Value >= dateDebut).Include(x=>x.Evenements).ToList();
                utilisateur.Grades.Armes = listeArme.First(x => x.Id == utilisateur.Grades.ArmesId);
            }

            //chargement des jours (avec indication si jour férié ou non)
            var listePcp = Db.Permissions.Where(x => x.Date >= dateDebut && x.Date <= dateFinMois && x.TypePerm == TypePermEnum.PCP).Select(x => x.Date).ToList();
            var listeRtt = Db.Permissions.Where(x => x.Date >= dateDebut && x.Date <= dateFinMois && x.TypePerm == TypePermEnum.RTT).Select(x => x.Date).ToList();
            data.ListeJours = new List<JourViewModel>();
            for (var i = 1; i <= dateFinMois.Day; i++)
            {
                var dateBoucle = new DateTime(date.Year, date.Month, i);
                data.ListeJours.Add(new JourViewModel
                {
                    Date = new DateTime(date.Year,date.Month,i),
                    LettreJour = DateUtils.GetJourDiminutif(new DateTime(date.Year,date.Month,i)),
                    IsFerie = DateUtils.IsFerie(dateBoucle) || DateUtils.IsWeekEnd(dateBoucle),
                    IsRtt = listeRtt.Contains(dateBoucle),
                    IsPcp = listePcp.Contains(dateBoucle)
                });
            }
            return data;
        }


        #region page principale
        /// <summary>
        /// Charge la apge du planning
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(GetData(DateTime.Today));
        }

        /// <summary>
        /// Charge le planning du mois suivant
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ActionName("Index"), SubmitButtonSelector(Name="NextMonth")]
        public ActionResult NextMonth()
        {
            var date = DateUtils.StringEnDate(Request.Form["inputDate"]);
            var data =
                GetData(date.Month >= 12
                    ? new DateTime(date.Year + 1, 1, 1)
                    : new DateTime(date.Year, date.Month + 1, 1));
            return View(data);
        }
        
        /// <summary>
        /// Charge le planning du mois précédent
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ActionName("Index"), SubmitButtonSelector(Name = "PreviousMonth")]
        public ActionResult PreviousMonth()
        {
            var date = DateUtils.StringEnDate(Request.Form["inputDate"]);
            var data =
                GetData(date.Month <= 1
                    ? new DateTime(date.Year - 1, 12, 1)
                    : new DateTime(date.Year, date.Month - 1, 1));
            return View(data);
        }

        #endregion
    }
}

GestionPlanning/Controllers/UtilisateursController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using GestionPlanning.Abstract;
using GestionPlanning.Context;
using GestionPlanning.Enum;
using GestionPlanning.Models;
using GestionPlanning.Utils;

namespace GestionPlanning.Controllers
{
    /// <summary>
    /// Controleur de la gestion des utilisateurs
    /// </summary>
    [Authorize(Roles = "ADMINISTRATEUR, UTILISATEUR")]
    public class UtilisateursController : AbstractControl
    {

        #region administration

        /// <summary>
        /// Charge la page de listing des utilisateurs
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "ADMINISTRATEUR")]
        public ActionResult Index()
        {
            var utilisateurs = Db.Utilisateurs.Where(x=> x.Etat == EtatEnum.ACTIF).OrderBy(x => x.Nom).ThenBy(x => x.Prenom).Include(u => u.Grades).Include(u => u.Poles);
            return View(utilisateurs.ToList());
        }

        /// <summary>
        /// CHarge la page de détail des utilisateurs
        /// </summary>
        /// <param name="id">l'id de l'utilisateur à consulter</param>
        /// <returns></returns>
        [Authorize(Roles = "ADMINISTRATEUR")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var utilisateurs = Db.Utilisateurs.Find(id);
            if (utilisateurs == null)
            {
                return HttpNotFound();
            }
            return View(utilisateurs);
        }

        /// <summary>
        /// Charge la page de création d'un utilisateur
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "ADMINISTRATEUR")]
        public ActionResult Create()
        {
            ViewBag.GradesId = new SelectList(Db.Grades.Where(x => x.Etat == EtatEnum.ACTIF && x.ArmesId == 1).ToList(), "Id", "Nom");
            ViewBag.ArmesId = new SelectList(Db.Armes.Where(x => x.Etat == EtatEnum.ACTIF).ToList(), "Id", "Nom");
            ViewBag.PolesId = new SelectList(Db.Poles.Where(x =>x.Etat == EtatEnum.ACTIF).ToList(), "Id", "Nom");
            return View(new Utilisateurs {Etat = EtatEnum.ACTIF, Role = RoleEnum.UTILISATEUR, MotDePasse = CryptUtils.GeneratePassword(9,true,true,true)});
        }

        /// <summary>
        /// Chang ela liste des grades lors d'un changement d'arme
        /// </summary>
        /// <param name="id">l'id de la nouvelle arme</param>
        /// <returns></returns>
        public ActionResult ChangeArme(int id)
        {
            var liste = Db.Grades.Where(x => x.ArmesId == id && x.Etat == EtatEnum.ACTIF).Select(x => new { x.Id, x.Nom }).ToList();
            return Json(liste);
        }
        
        /// <summary>
        /// Créer un utilisateur
        /// </summary>
        /// <param name="utilisateurs">l'utilisateur à créer</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMINISTRATEUR")]
        public async Task<ActionResult> Create(Utilisateurs utilisateurs)
        {
            if (Db.Utilisateurs.Count(x => x.Email == utilisateurs.Email && x.Etat == EtatEnum.ACTIF) > 0)
            {
                ModelState.AddModelError("Email", "Cette adresse est déjà présente!");
            }

            if (ModelState.IsValid)
            {
                Utilisateurs user;
                var isAjout = false;
                //si l'adresse existe en base c'est que c'est un utilisateur périmé, donc on le réactive
                if(Db.Utilisateurs.Count(x => x.Email == utilisateurs.Email) > 0)
                {
                    user = Db.Utilisateurs.First(x => x.Email == utilisateurs.Email);
                }
                else
                {
                    user = Db.Utilisateurs.Create();
                    isAjout = true;
                }

                var motDePasse = CryptUtils.GeneratePassword(9, true, true, true);
                user.MotDePasse = CryptUtils.GenerateHashPassword(motDePasse);
                user.Email = utilisateurs.Email.ToLower();
                user.Nom = StringUtils.FirstLetterUpper(utilisateurs.Nom.ToLower());
                user.Prenom = StringUtils.FirstLetterUpper(utilisateurs.Prenom.ToLower());
                user.Nid = utilisateurs.Nid;
                user.Pnia = utilisateurs.Pnia;
                user.Role = utilisateurs.Role;
                user.GradesId = utilisateurs.GradesId;
                user.PolesId = utilisateurs.PolesId;
                user.Etat = EtatEnum.ACTIF;

                if (isAjout)
                {
                    Db.Entry(user).State = EntityState.Added;
                    Db.Utilisateurs.Add(user);
                }
                else
                {
                    Db.Entry(user).State = EntityState.Modified;
                }
                Db.SaveChanges();

                //envoi du mail
                var mail = Db.Mails.First(x => x.NomUnique == ContexteStatic.EnvoiCreationCompte);
                var corpsMessage = StringUtils.CopyString(mail.Corps);
                corpsMessage = corpsMessage.Replace("%NOMAPPLI%", ContexteApplication.Application.NomAppli);
                corpsMessage = corpsMessage.Replace("%LOGIN%", user.Email);
                corpsMessage = corpsMessage.Replace("%MOTDEPASSE%", motDePasse);
                await MailUtils.SendMail(user.Email, mail.Objet, corpsMessage);

                return RedirectToAction("Index");
            }

            ViewBag.GradesId = new SelectList(Db.Grades.Where(x => x.Etat == EtatEnum.ACTIF && x.ArmesId == utilisateurs.ArmesId).ToList(), "Id", "Nom");
            ViewBag.ArmesId = new SelectList(Db.Armes.Where(x => x.Etat == EtatEnum.ACTIF).ToList(), "Id", "Nom");
            ViewBag.PolesId = new SelectList(Db.Poles.Where(x => x.Etat == EtatEnum.ACTIF).ToList(), "Id", "Nom");
            return View(utilisateurs);
        }

        /// <summary>
        /// Charge la page de modification d'un utilisateur
        /// </summary>
        /// <param name="id">l'id de l'utilisateur à modifier</param>
        /// <returns></returns>
        [Authorize(Roles = "ADMINISTRATEUR")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var utilisateurs = Db.Utilisateurs.Find(id);
            if (utilisateurs == null)
            {
                return HttpNotFound();
            }

            utilisateurs.ArmesId = utilisateurs.Grades.ArmesId;
            ViewBag.ArmesId = new SelectList(Db.Armes.Where(x => x.Etat == EtatEnum.ACTIF).ToList(), "Id", "Nom",utilisateurs.ArmesId);
            ViewBag.GradesId = new SelectList(Db.Grades.Where(x => x.Etat == EtatEnum.ACTIF && x.ArmesId == utilisateurs.ArmesId).ToList(), "Id", "Nom", utilisateurs.GradesId);
            ViewBag.PolesId = new SelectList(Db.Poles.Where(x => x.Etat == EtatEnum.ACTIF).ToList(), "Id", "Nom", utilisateurs.PolesId);
            return View(utilisateurs);
        }
        
        /// <summary>
        /// Modifie un utilisateur en base
        /// </summary>
        /// <param name="utilisateurs"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMINISTRATEUR")]
        public ActionResult Edit(Utilisateurs utilisateurs)
        {
            if (Db.Utilisateurs.Count(x => x.Email == utilisateurs.Email && x.Id != utilisateurs.Id) > 0)
            {
                ModelState.AddModelError("Email", "Cette adresse est déjà présente!");
            }


            if (ModelState.IsValid)
            {
                var user = Db.Utilisateurs.Find(utilisateurs.Id);

                if (user != null)
                {
                    user.Email = utilisateurs.Email;
                    user.GradesId = utilisateurs.GradesId;
                    user.Role = utilisateurs.Role;
                    user.Nom = utilisateurs.Nom;
                    user.Prenom = utilisateurs.Prenom;
                    user.PolesId = utilisateurs.PolesId;
                    user.Nid = utilisateurs.Nid;
                    user.Pnia = utilisateurs.Pnia;
                    
                    Db.Entry(user).State = EntityState.Modified;
                    Db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("Nom", "Cet utilisateur est introuvable");
                }
            }
            ViewBag.GradesId = new SelectList(Db.Grades.Where(x => x.Etat == EtatEnum.ACTIF && x.ArmesId == utilisateurs.ArmesId).ToList(), "Id", "Nom");
            ViewBag.ArmesId = new SelectList(Db.Armes.Where(x => x.Etat == EtatEnum.ACTIF).ToList(), "Id", "Nom");
            ViewBag.PolesId = new SelectList(Db.Poles, "Id", "Nom", utilisateurs.PolesId);
            return View(utilisateurs);
        }

        /// <summary>
        /// Charge la page de supression d'un utilisateur
        /// </summary>
        /// <param name="id">l'id de l'utilisateur à supprimer</param>
        /// <returns></returns>
        [Authorize(Roles = "ADMINISTRATEUR")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var utilisateurs = Db.Utilisateurs.Find(id);
            if (utilisateurs == null)
            {
                return HttpNotFound();
            }
            return View(utilisateurs);
        }

        /// <summary>
        /// Périme un utilisateur en base
        /// </summary>
        /// <param name="id">l'id de l'utilisateur à périmer</param>

GestionPlanning/Views/Utilisateurs/Annuaire.cshtml
@model System.Linq.IOrderedEnumerable<GestionPlanning.Models.Utilisateurs>
@{
    ViewBag.Title = "Annuaire";
    var lettreEnCours = ' ';
}

<h2>Annuaire</h2>
<table style="width:400px;">
@foreach (var item in Model)
{
    if (lettreEnCours != item.Nom[0])
    {
        lettreEnCours = item.Nom[0];

        <tr>
            <td>
                <p style="background-color: grey; text-align: center;">@lettreEnCours</p>
            </td>
        </tr>
    }
    <tr>
        <td>
            <p style="background-color: white">
                <table style="width:400px;">
                    <tr>
                        <td style="width:200px;">@item.Nom.ToUpper() @item.Prenom</td>
                        <td style="width:100px;"><b>@item.Poles.Nom</b></td>
                        <td style="width:100px;">@item.Pnia</td>
                    </tr>
                </table>
            </p>
        </td>
    </tr>

}

</table>

GestionPlanning/Views/Utilisateurs/ChangeInfoPerso.cshtml
@model GestionPlanning.Models.Utilisateurs

@{
    ViewBag.Title = "Modifier mes données";
}

<h2>Modifier mes données</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <script>
        $(document).ready(function() {
            $('#saveButton').click(function() {
                $(this).prop("disabled", true);
                if (!$('form').valid()) {
                    $(this).prop("disabled", false);
                    return false;
                }
                $('form').submit();
            });
        });
    </script>



    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.MotDePasse)
        @Html.HiddenFor(model => model.Nom)
        @Html.HiddenFor(model => model.Prenom)
        @Html.HiddenFor(model => model.Email)
        @Html.HiddenFor(model => model.GradesId)
        @Html.HiddenFor(model => model.PolesId)
        @Html.HiddenFor(model => model.Role)
        @Html.HiddenFor(model => model.Etat)
        @Html.HiddenFor(model => model.Nid)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Pnia)
                @Html.TextBoxFor(model => model.Pnia, new { @class = "form-control", style="width:80px;" } )
                @Html.ValidationMessageFor(model => model.Pnia, "", new {@class = "text-danger"})
        </div>


        <div class="form-group">
                <input type="submit" value="Sauvegarder" class="btn btn-default" id="saveButton"/>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Modifier mon mot de passe", "ChangePasswordPerso")
    <br/><br/>
    @Html.ActionLink("Retour à l'acceuil", "Index", "Planning")
</div>

GestionPlanning/Views/Utilisateurs/ChangePassword.cshtml
@model GestionPlanning.Models.Utilisateurs

@{
    ViewBag.Title = "Modifier un mot de passe";
}

<h2>Modifier un mot de passe</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Email)
        @Html.HiddenFor(model => model.Nom)
        @Html.HiddenFor(model => model.Prenom)
        @Html.HiddenFor(model => model.GradesId)
        @Html.HiddenFor(model => model.PolesId)
        @Html.HiddenFor(model => model.Role)
        @Html.HiddenFor(model => model.Nid)
        @Html.HiddenFor(model => model.Pnia)

        <div class="form-group">
            @Html.LabelFor(model => model.MotDePasse)
                @Html.PasswordFor(model => model.MotDePasse, new { @class="form-control"})
                @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Page précédente", "Index")
</div>

GestionPlanning/Views/Utilisateurs/Create.cshtml
@model GestionPlanning.Models.Utilisateurs

@{
    ViewBag.Title = "Créer un utilisateur";
}

<h2>Ajouter un utilisateur</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Etat)
        @Html.HiddenFor(model => model.MotDePasse)

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nom)
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prenom)
                @Html.TextBoxFor(model => model.Prenom, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Prenom, "", new {@class = "text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nid)
                @Html.TextBoxFor(model => model.Nid, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Nid, "", new {@class = "text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pnia)
                @Html.TextBoxFor(model => model.Pnia, new { @class = "form-control", style = "width:80px;" } )
                @Html.ValidationMessageFor(model => model.Pnia, "", new { @class = "text-danger" })
        </div>

        <script>

            function ChangeArme(id) {
                var url = '@Url.Action("ChangeArme", "Utilisateurs")';

                $.ajax(
                {
                    url: url,
                    data: { id : id},
                    type: "POST",
                    success:
                        function (view) {
                            $("#ListboxGrade").selectedIndex = -1;
                            $("#ListboxGrade").empty();
                            $.each(view, function (index) {
                                $('#ListboxGrade').append($('<option>', {
                                    value: view[index]["Id"],
                                    text: view[index]["Nom"]
                                }));
                            });
                        }
                }
                );
            }
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.ArmesId, "Armes" )
                @Html.DropDownList("ArmesId", null, new { @class = "form-control", onchange= "ChangeArme(this.value)" })
                @Html.ValidationMessageFor(model => model.ArmesId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GradesId, "Grades")
                @Html.DropDownList("GradesId", null, new { @class = "form-control", id= "ListboxGrade" })
                @Html.ValidationMessageFor(model => model.GradesId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role)
                @Html.EnumDropDownListFor(model => model.Role,null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolesId, "Poles")
                @Html.DropDownList("PolesId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PolesId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
                <input type="submit" value="Ajouter" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Page précédente", "Index")
</div>

GestionPlanning/Views/Utilisateurs/Edit.cshtml
@model GestionPlanning.Models.Utilisateurs

@{
    ViewBag.Title = "Modifier un utilisateur";
}

<h2>Modifier un utilisateur</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Etat)
        @Html.HiddenFor(model => model.MotDePasse)

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
                @Html.TextBoxFor(model => model.Email,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nom)
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prenom)
                @Html.TextBoxFor(model => model.Prenom, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Prenom, "", new {@class = "text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nid)
                @Html.TextBoxFor(model => model.Nid, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Nid, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pnia)
                @Html.TextBoxFor(model => model.Pnia,  new { @class = "form-control",style="width:80px;"  })
                @Html.ValidationMessageFor(model => model.Pnia, "", new { @class = "text-danger" })
        </div>

        <script>

            function ChangeArme(id) {
                var url = '@Url.Action("ChangeArme", "Utilisateurs")';

                $.ajax(
                {
                    url: url,
                    data: { id : id},
                    type: "POST",
                    success:
                        function (view) {
                            $("#ListboxGrade").selectedIndex = -1;
                            $("#ListboxGrade").empty();
                            $.each(view, function (index) {
                                $('#ListboxGrade').append($('<option>', {
                                    value: view[index]["Id"],
                                    text: view[index]["Nom"]
                                }));
                            });
                        }
                }
                );
            }
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.ArmesId, "Armes")
                @Html.DropDownList("ArmesId", null, new { @class = "form-control", onchange = "ChangeArme(this.value)" })
                @Html.ValidationMessageFor(model => model.ArmesId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GradesId, "Grade")
                @Html.DropDownList("GradesId", null, new { @class = "form-control", id = "ListboxGrade" })
                @Html.ValidationMessageFor(model => model.GradesId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role,  new { @class = "control-label col-md-2" })
                @Html.EnumDropDownListFor(model => model.Role,null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolesId, "Pole")
                @Html.DropDownList("PolesId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PolesId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
                <input type="submit" value="Modifier" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Page précédente", "Index")
</div>