GestionPlanning/Models/Evenements.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using GestionPlanning.Enum;

namespace GestionPlanning.Models
{
    /// <summary>
    /// Model des évènements à enregistrer en base (sortie cohésion, resto....)
    /// </summary>
    [Table("evenements")]
    public class Evenements
    {
        /// <summary>
        /// l'identifiant unique
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// le titre de l'évènement
        /// </summary>
        [Required(ErrorMessage = "Ce champ est requis")]
        [DataType(DataType.Text)]
        [DisplayName("Titre")]
        [Column("Titre", TypeName = "VARCHAR")]
        [MaxLength(50, ErrorMessage = "Ce champ pdoit faire au maximum 50 caractères")]
        public string Titre { get; set; }

        /// <summary>
        /// la première date de l'évènement
        /// </summary>
        [Required(ErrorMessage = "Ce champ est requis")]
        [DisplayName("Date (obligatoire)")]
        [Column("Date", TypeName = "DATETIME")]
        [DataType(DataType.DateTime,ErrorMessage = "Ce champ doit être une date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }
        
        /// <summary>
        /// la demi journée où aura lieu cet évènement
        /// </summary>
        [Required(ErrorMessage = "Ce champ est requis")]
        [DisplayName("Demi journée")]
        [Column("DemiJournee", TypeName = "INT")]
        public DemiJourneeEnum DemiJournee { get; set; }

        /// <summary>
        /// la dexuième date de l'évènement
        /// </summary>
        [DisplayName("Deuxième date (optionnelle)")]
        [Column("DateB", TypeName = "DATETIME")]
        [DataType(DataType.DateTime,ErrorMessage = "Ce champ doit être une date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DateB { get; set; }

        /// <summary>
        /// la demi journée de la deuxième date
        /// </summary>
        [DisplayName("Demi journée")]
        [Column("DemiJourneeB", TypeName = "INT")]
        public DemiJourneeEnum? DemiJourneeB { get; set; }

        /// <summary>
        /// la trosième date de l'évènement
        /// </summary>
        [DisplayName("Troisième date (optionnelle) ")]
        [Column("DateC", TypeName = "DATETIME")]
        [DataType(DataType.DateTime,ErrorMessage = "Ce champ doit être une date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DateC { get; set; }

        /// <summary>
        /// la demi journée de la troisième date
        /// </summary>
        [DisplayName("Demi journée")]
        [Column("DemiJourneeC", TypeName = "INT")]
        public DemiJourneeEnum? DemiJourneeC { get; set; }

        /// <summary>
        /// la date limite de réponse de l'évènement
        /// </summary>
        [DisplayName("Date limite de réponse ")]
        [Column("DateVerrou", TypeName = "DATETIME")]
        [DataType(DataType.DateTime,ErrorMessage = "Ce champ doit être une date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DateVerrou { get; set; }

        
        /// <summary>
        /// un commentaire éventuel de l'organisateur
        /// </summary>
        [DataType(DataType.MultilineText)]
        [DisplayName("Commentaire")]
        [Column("Commentaire", TypeName = "VARCHAR")]
        [MaxLength(500, ErrorMessage = "Ce champ pdoit faire au maximum 500 caractères")]
        public string Commentaire { get; set; }

        /// <summary>
        /// l'id du créateur de l'évènement
        /// </summary>
        [Required(ErrorMessage = "Ce champ est requis")]
        [Column("CreateurId", TypeName = "INT")]
        public int CreateurId { get; set; }

        /// <summary>
        /// l'objet du créateur
        /// </summary>
        [ForeignKey("CreateurId")]
        [DisplayName("Créateur")]
        public virtual Utilisateurs Createur { get; set; }
        
        /// <summary>
        /// la liste des utilisateurs associé à cet évènement
        /// </summary>
        public virtual ICollection<EvenementsUtilisateurs> EvenementsUtilisateurs { get; set; }


        ////////POUR LA CONSULTATION D'UN EVENEMENT
        /// <summary>
        /// Pour la consultation d'un utilisateur, indique le numéro de la date sélectionné 1= Date, 2=DateB, 3=DateC
        /// </summary>
        [NotMapped]
        public int SelectedDate { get; set; }

        /// <summary>
        /// Pour la consultation d'un utilisateur, indique si cet utilisateur qui le consulte est présent
        /// </summary>
        [NotMapped]
        public bool? IsUtilisateurPresent { get; set; }

        /// <summary>
        /// Pour la consultation d'un utilisateur, indique le commentaire de l'utilisateur qui consulte
        /// </summary>

        [NotMapped]
        [MaxLength(500)]
        public string CommentaireUtilisateur { get; set; }

    }
}

GestionPlanning/Controllers/EvenementsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using GestionPlanning.Abstract;
using GestionPlanning.Context;
using GestionPlanning.Enum;
using GestionPlanning.Models;
using GestionPlanning.Utils;
using GestionPlanning.ViewModel;
using Novacode;

namespace GestionPlanning.Controllers
{
    /// <summary>
    /// Controleur pour la gestion des évènements
    /// </summary>
    [Authorize(Roles = "ADMINISTRATEUR,UTILISATEUR")]
    public class EvenementsController : AbstractControl
    {
        /// <summary>
        /// Génère un viewmodel adapté à la création / modification
        /// </summary>
        /// <param name="evenement"> l'évènement ViewModel si il existe déjà, sinon null</param>
        /// <returns>the even</returns>
        private EvenementViewModel GenerateViewModelCreate(EvenementViewModel evenement)
        {
            var even = evenement ?? new EvenementViewModel ();

            if (evenement?.EvenementsCre != null)
            {
                even.EvenementsCre = evenement.EvenementsCre;
            }
            else
            {
                even.EvenementsCre = new Evenements { DemiJournee = DemiJourneeEnum.MATIN, DateVerrou = null, Date = DateUtils.GetAujourdhui() };
            }

            //chargement des poles sélectionables
            even.PoleItems = Db.Poles.Where(x => x.Etat == EtatEnum.ACTIF).ToList();

            //chargement des utilisateurs sélectionable
            even.UtilisateursItems = Db.Utilisateurs.Where(x => x.Etat == EtatEnum.ACTIF).OrderBy(x => x.Nom).ThenBy(x => x.Prenom).ToList();
            return even;
        }

        /// <summary>
        /// Génère un view model pour l'affichage de la liste des évènements auquel l'utilisateur participe ou à crée
        /// </summary>
        /// <returns>the even</returns>
        public EvenementViewModel GenerateEvenementsParticipe()
        {
            var dateLim = DateUtils.GetAujourdhui();
            //on ne prend pas les évènements passé depuis 3 jours
            dateLim = dateLim.AddDays(-3);
            var even  = new EvenementViewModel();
            var id = GetIdUtilisateurConnecte();
            even.EvenementsPersoCreer = Db.Evenements.Where(x => x.CreateurId == id && x.Date > dateLim).ToList();
            even.EvenementsParticipe = (from e in Db.Evenements.Where(x => x.Date > dateLim)
                join eu in Db.EvenementsUtilisateurs
                on e.Id equals eu.EvenementsId
                where eu.UtilisateursId == id
                select e ).ToList();
            return even;
        }



        /// <summary>
        /// Charge la page des évènements d'un utilisateur
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult MesEvenements()
        {
            return View(GenerateEvenementsParticipe());
        }


        #region Création d'évènements
        /// <summary>
        /// Charge la page de création d'un évènement
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View(GenerateViewModelCreate(null));
        }

        /// <summary>
        /// Créer un évènement à partir du viewModel
        /// </summary>
        /// <param name="evenementCreer">le viewModel contenant les infos pour créer l'évènement</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EvenementViewModel evenementCreer)
        {
            if (ModelState.IsValid)
            {
                //controle de la dateA
                if (evenementCreer.EvenementsCre.Date < DateUtils.GetAujourdhui())
                {
                    ModelState.AddModelError("EvenementsCre.Date", "La date doit être supérieur à la date du jour");
                }

                if (evenementCreer.EvenementsCre.DemiJournee != DemiJourneeEnum.APRESMIDI && evenementCreer.EvenementsCre.DemiJournee != DemiJourneeEnum.MATIN)
                {
                    ModelState.AddModelError("EvenementsCre.DemiJournee", "Il est nécéssaire de préciser la demi journée");
                }

                //controle de la dateB
                if (evenementCreer.EvenementsCre.DateB != null)
                {
                    if (evenementCreer.EvenementsCre.DemiJourneeB != DemiJourneeEnum.APRESMIDI && evenementCreer.EvenementsCre.DemiJourneeB != DemiJourneeEnum.MATIN)
                    {
                        ModelState.AddModelError("EvenementsCre.DemiJourneeB", "Il est nécéssaire de préciser la demi journée");
                    }

                    if (evenementCreer.EvenementsCre.DateB < DateUtils.GetAujourdhui())
                    {
                        ModelState.AddModelError("EvenementsCre.DateB", "La date doit être supérieur à la date du jour");
                    }

                    if (evenementCreer.EvenementsCre.DateB == evenementCreer.EvenementsCre.Date &&
                        evenementCreer.EvenementsCre.DemiJourneeB == evenementCreer.EvenementsCre.DemiJournee)
                    {
                        ModelState.AddModelError("EvenementsCre.DateB", "cette date est identique à la première date");
                    }
                }

                //controle de la dateC
                if (evenementCreer.EvenementsCre.DateC != null)
                {
                    if (evenementCreer.EvenementsCre.DemiJourneeC != DemiJourneeEnum.APRESMIDI && evenementCreer.EvenementsCre.DemiJourneeC != DemiJourneeEnum.MATIN)
                    {
                        ModelState.AddModelError("EvenementsCre.DemiJourneeC", "Il est nécéssaire de préciser la demi journée");
                    }

                    if (evenementCreer.EvenementsCre.DateC < DateUtils.GetAujourdhui())
                    {
                        ModelState.AddModelError("EvenementsCre.DateC", "La date doit être supérieur à la date du jour");
                    }

                    if ((evenementCreer.EvenementsCre.DateC == evenementCreer.EvenementsCre.Date && evenementCreer.EvenementsCre.DemiJourneeC == evenementCreer.EvenementsCre.DemiJournee) ||
                        (evenementCreer.EvenementsCre.DateB != null && evenementCreer.EvenementsCre.DemiJourneeB != null &&
                         evenementCreer.EvenementsCre.DateC == evenementCreer.EvenementsCre.DateB && evenementCreer.EvenementsCre.DemiJourneeC == evenementCreer.EvenementsCre.DemiJourneeB))
                    {
                        ModelState.AddModelError("EvenementsCre.DateC", "cette date est identique à une des dates ci dessus");
                    }
                }


                //control de la date de verrouillage
                if (evenementCreer.EvenementsCre.DateVerrou != null)
                {
                    if (evenementCreer.EvenementsCre.DateVerrou <= DateUtils.GetAujourdhui() ||
                        evenementCreer.EvenementsCre.DateVerrou > evenementCreer.EvenementsCre.Date ||
                        (evenementCreer.EvenementsCre.DateB != null && evenementCreer.EvenementsCre.DateVerrou > evenementCreer.EvenementsCre.DateB) ||
                        (evenementCreer.EvenementsCre.DateC != null && evenementCreer.EvenementsCre.DateVerrou > evenementCreer.EvenementsCre.DateC) )
                    {
                        ModelState.AddModelError("EvenementsCre.DateVerrou", "La date limite est incorrecte");
                    }
                }

                //recup des utilisateurs / poles sélectionnés
                var selectedIdsPole = Request.Form.GetValues("PolesIdChecked");
                var selectedIdsUser = Request.Form.GetValues("UtilisateursIdChecked");

                //control de la sélection du personnel
                if (!StringUtils.CheckStringArrayContainsInt(selectedIdsPole) && !StringUtils.CheckStringArrayContainsInt(selectedIdsUser))
                {
                    ModelState.AddModelError("selectionError", "Aucune personne de sélectionné");
                }

                 if (ModelState.IsValid)
                 {
                     var selectedUserToSend = Request.Form["radioSelect"] == "0";
                    //si la date de verrouillage est null c'est que c'est la meme que la date de l'évènement (la plus grande des trois possibles)
                    evenementCreer.EvenementsCre.DateVerrou = (evenementCreer.EvenementsCre.DateVerrou.HasValue)
                         ? evenementCreer.EvenementsCre.DateVerrou
                         : DateUtils.GetPlusGrandeDate(evenementCreer.EvenementsCre.Date, evenementCreer.EvenementsCre.DateB, evenementCreer.EvenementsCre.DateC);
                    
                    //récup de l'évènement
                    var even = evenementCreer.EvenementsCre;
                    even.CreateurId = GetIdUtilisateurConnecte();
                    Db.Evenements.Add(even);

                    //récup des utilisateurs à inviter
                    List<Utilisateurs> listeUser;
                    if (selectedUserToSend)
                    {
                        //récup de la lsite des utilisateurs sélectionné
                        var listeInt = new List<int>();
                        foreach (var value in selectedIdsUser)
                        {
                            int i;
                            if(int.TryParse(value, out i))
                            {
                                listeInt.Add(i);
                            }
                        }

                        listeUser = Db.Utilisateurs.Where(
                            x => listeInt.Contains(x.Id)).ToList();
                    }
                    else
                    {
                        //récup de la lsite des utilisateurs sélectionné par poles

GestionPlanning/Views/Evenements/Consult.cshtml
@using GestionPlanning.Utils
@using GridMvc.Html
@model GestionPlanning.Models.Evenements

@{
    ViewBag.Title = "Consulter un évènement";
}

<h2>Consulter un évènement</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model =>  model.Id)

    <div class="form-group">
        <h2>@Html.DisplayFor(model => model.Titre)</h2>
        <p><b>Créateur :</b> @Html.DisplayFor(model => model.Createur.Nom) @Html.DisplayFor(model => model.Createur.Prenom)</p>
        <p><b>Date limite de réponse  :</b> @Html.DisplayFor(model => model.DateVerrou)</p>
        <p><b>Commentaire :</b> @Html.DisplayFor(model => model.Commentaire)</p>

        @if (Model.DateVerrou < DateUtils.GetAujourdhui() || 
            (Model.SelectedDate == 1 && Model.Date < DateUtils.GetAujourdhui()) ||
            (Model.SelectedDate == 2 && Model.DateB < DateUtils.GetAujourdhui()) ||
            (Model.SelectedDate == 3 && Model.DateC < DateUtils.GetAujourdhui()))
        {
            <p><b>Ma participation : (date limite de réponse dépassé)</b></p>
            <p>
                Présent ?
                @Html.RadioButton("IsPresentPresence", 1,new { disabled="disabled"}) Oui @Html.RadioButton("IsPresentPresence", 0, new { disabled = "disabled" }) Non
                @Html.ValidationMessage("IsPresentPresence", "", new { @class = "text-danger" })
            </p>
            <p>
                <b>Commentaire</b>
                @Html.TextBox("CommentairePresence", null, new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessage("CommentairePresence", "", new { @class = "text-danger" })
            </p>
        }
        else
        {
            <p><b>Ma participation :</b></p>

            <p>
                <b>Date :</b>
                @Html.ValidationMessage("IsDateSelect", "", new { @class = "text-danger" })
                <div>@Html.RadioButtonFor(model => model.SelectedDate, 1) @Html.DisplayFor(model => model.Date) @Html.Label("-") @Html.DisplayFor(model => model.DemiJournee)</div>
                @if (Model.DateB != null)
                {
                    <div>@Html.RadioButtonFor(model => model.SelectedDate, 2) @Html.DisplayFor(model => model.DateB) @Html.Label("-") @Html.DisplayFor(model => model.DemiJourneeB)</div>
                }
                @if (Model.DateC != null)
                {
                    <div>@Html.RadioButtonFor(model => model.SelectedDate, 3) @Html.DisplayFor(model => model.DateC) @Html.Label("-") @Html.DisplayFor(model => model.DemiJourneeC)</div>
                }
            </p>
             <p>
                Présent ?
                @Html.RadioButtonFor(model => model.IsUtilisateurPresent, true) Oui @Html.RadioButtonFor(model => model.IsUtilisateurPresent, false) Non
                @Html.ValidationMessage("IsPresentPresence", "", new { @class = "text-danger" })
            </p>
            <p>
                <b>Commentaire</b>
                @Html.TextBoxFor(model => model.CommentaireUtilisateur, new { @class = "form-control" })
                @Html.ValidationMessage("CommentairePresence", "", new { @class = "text-danger" })
            </p>
            <div class="form-group">
                <input type="submit" value="Valider" class="btn btn-default" name="ValidConsult"/> | @Html.ActionLink("Page précédente", "MesEvenements")
            </div>
        }
        

        <div class="form-group">
            <input type="submit" value="Télécharger" class="btn btn-default" name="DownloadConsult"/>
        </div>

        <p><b>Participants :</b></p>
        @Html.Grid(Model.EvenementsUtilisateurs).Columns(columns =>
   {
       columns.Add(model => model.Utilisateurs.Nom).Titled("Nom").Sortable(true);
       columns.Add(model => model.Utilisateurs.Prenom).Titled("Prenom").Sortable(false);
       columns.Add().Titled("Date").RenderValueAs(model => (model.DateSelected.HasValue) ? DateUtils.GetDateFormat(model.DateSelected.Value,"yyyy-MM-dd")+"-"+model.DemiJourneeSelected : " ").Sortable(true);
       columns.Add().Titled("Est présent").RenderValueAs(model => (model.IsPresent.HasValue) ?((model.IsPresent.Value)?"OUI":"NON"):" ").Sortable(true);
       columns.Add(model => model.Commentaire).Titled("Commentaire");
   }).WithPaging(10)
    </div>
}

GestionPlanning/Views/Evenements/Create.cshtml
@using GridMvc.Html
@model GestionPlanning.ViewModel.EvenementViewModel
@{
    ViewBag.Title = "Créer un évènement";
}

<h2>Créer un évènement</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <script>
        $(document).ready(function () {
            $('#saveButton').click(function () {
                $(this).prop("disabled", true);
                if (!$('form').valid())
                {
                    $(this).prop("disabled",false);
                    return false;
                }
                $('form').submit();
            });
        });
    </script>


    <div class="form-group">
        @Html.LabelFor(model => model.EvenementsCre.Titre)
            @Html.TextBoxFor(model => model.EvenementsCre.Titre, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EvenementsCre.Titre, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EvenementsCre.Date)
        <input type="date" id="EvenementsCre.Date" name="EvenementsCre.Date" value="@($"{Model.EvenementsCre.Date:yyyy-MM-dd}")" class="form-control" />
        @Html.EnumDropDownListFor(model => model.EvenementsCre.DemiJournee, null, new {@class = "form-control", style = "margin-top:5px;"})
        @Html.ValidationMessageFor(model => model.EvenementsCre.DemiJournee, "", new {@class = "text-danger"})
        @Html.ValidationMessageFor(model => model.EvenementsCre.Date, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EvenementsCre.DateB)
        <input type="date" id="EvenementsCre.DateB" name="EvenementsCre.DateB" value="@($"{Model.EvenementsCre.DateB:yyyy-MM-dd}")" class="form-control" />

        @Html.EnumDropDownListFor(model => model.EvenementsCre.DemiJourneeB, "", new {@class = "form-control", style = "margin-top:5px;"})
        @Html.ValidationMessageFor(model => model.EvenementsCre.DemiJourneeB, "", new {@class = "text-danger"})
        @Html.ValidationMessageFor(model => model.EvenementsCre.DateB, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EvenementsCre.DateC)
        <input type="date" id="EvenementsCre.DateC" name="EvenementsCre.DateC" value="@($"{Model.EvenementsCre.DateC:yyyy-MM-dd}")" class="form-control" />

        @Html.EnumDropDownListFor(model => model.EvenementsCre.DemiJourneeC, null, new { @class = "form-control", style = "margin-top:5px;" })
        @Html.ValidationMessageFor(model => model.EvenementsCre.DemiJourneeC, "", new { @class = "text-danger" })
        @Html.ValidationMessageFor(model => model.EvenementsCre.DateC, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EvenementsCre.DateVerrou)
        <input type="date" id="EvenementsCre.DateVerrou" name="EvenementsCre.DateVerrou" value="@($"{Model.EvenementsCre.DateVerrou:yyyy-MM-dd}")" class="form-control"/>
        @Html.ValidationMessageFor(model => model.EvenementsCre.DateVerrou, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EvenementsCre.Commentaire)
            @Html.TextAreaFor(model => model.EvenementsCre.Commentaire, new { @class = "form-control", style = "width:300px; height: 100px;" })
            @Html.ValidationMessageFor(model => model.EvenementsCre.Commentaire, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <p style="margin-top: 80px;">Sélection par :</p>
        <script>
            function isactive(object) {
                if (object.value == 1) {
                    document.getElementById("divPoles").style.display = "block";
                    document.getElementById("divUtil").style.display = "none";
                    var elements = document.getElementById("SelectedPolesListbox").options;

                    for (var i = 0; i < elements.length; i++) {
                        elements[i].selected = false;
                    }


                } else {
                    document.getElementById("divPoles").style.display = "none";
                    document.getElementById("divUtil").style.display = "block";
                    var elements = document.getElementById("SelectedUtilisateursListbox").options;

                    for (var i = 0; i < elements.length; i++) {
                        elements[i].selected = false;
                    }
                }
            }
        </script>
        <label>
            @Html.RadioButton("radioSelect", 1, new
            {
                onclick = "isactive(this);"

            })
            Par poles
        </label>
        <label>
            @Html.RadioButton("radioSelect", 0, new
            {
                onclick = "isactive(this);"

            })
            Par utilisateurs
        </label>
        @Html.ValidationMessage("selectionError", "", new { @class = "text-danger" })
    </div>

    <div>
        <div id="divPoles" style="display: none">
            <p>Liste des pôles :</p>
            @Html.Grid(Model.PoleItems).Columns(columns =>
            {
                columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(o => Html.CheckBox("PolesIdChecked", false, new { name = "selectedPolesIds", value = o.Id }));
                columns.Add(model => model.Nom).Titled("Nom").Sortable(true).SetWidth(150);
            }).WithPaging(10)
        </div>

        <div id="divUtil" style="display: none">
            <p>Liste des utilisateurs : </p>
            @Html.Grid(Model.UtilisateursItems).Columns(columns =>
       {
       columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(o => Html.CheckBox("UtilisateursIdChecked", false, new { name = "selectedUtilisateursIds", value = o.Id }));
           columns.Add().Encoded(false).Sanitized(false).Sortable(true).SetWidth(150).RenderValueAs(o => o.Nom+" "+o.Prenom).Titled("Nom");
       }).WithPaging(10)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            <input type="submit" value="Créer" class="btn btn-default" id="saveButton"/>
        </div>
    </div>
}

GestionPlanning/Views/Evenements/MesEvenements.cshtml
@model GestionPlanning.ViewModel.EvenementViewModel

@{
    ViewBag.Title = "Mes évènements";
}

<h2>Mes évènements</h2>

@Html.ActionLink("Créer un évènement", "Create", "Evenements")
<p>Evènements dont je suis propriétaire :</p>
<table class="table">
    <tr>
        <th>
            Evènements
        </th>
        <th>
            Date
        </th>
        <th></th>
    </tr>
    @foreach (var even in Model.EvenementsPersoCreer)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => even.Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => even.Date)
                @Html.Label("-")
                @Html.DisplayFor(modelItem => even.DemiJournee)

                @if (even.DateB != null)
                {
                    @Html.Label(" --- ")
                    @Html.DisplayFor(modelItem => even.DateB)
                    @Html.Label("-")
                    @Html.DisplayFor(modelItem => even.DemiJourneeB)
                }

                @if (even.DateC != null)
                {
                    @Html.Label(" --- ")
                    @Html.DisplayFor(modelItem => even.DateC)
                    @Html.Label("-")
                    @Html.DisplayFor(modelItem => even.DemiJourneeC)
                }
            </td>
            <td>
                @Html.ActionLink("Modifier", "Edit", new { id = even.Id })
            </td>
        </tr>
    }
</table>

    <br/>
    <br/>

    <p>Evènements auquel je suis invité :</p>
<table class="table">
        <tr>
            <th>
                Evènements
            </th>
            <th>
                Date
            </th>
            <th></th>
        </tr>
        @foreach (var even in Model.EvenementsParticipe)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => even.Titre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => even.Date)
                    @Html.Label("-")
                    @Html.DisplayFor(modelItem => even.DemiJournee)

                    @if (even.DateB != null)
                {
                        @Html.Label(" --- ")
                        @Html.DisplayFor(modelItem => even.DateB)
                        @Html.Label("-")
                        @Html.DisplayFor(modelItem => even.DemiJourneeB)
                    }

                    @if (even.DateC != null)
                {
                        @Html.Label(" --- ")
                        @Html.DisplayFor(modelItem => even.DateC)
                        @Html.Label("-")
                        @Html.DisplayFor(modelItem => even.DemiJourneeC)
                    }
                </td>
                <td>
                    @Html.ActionLink("Consulter", "Consult", new { id = even.Id })
                </td>
            </tr>
        }
</table>